encryptionsalt: v1:4XmH4c3MoHk=:v1:5rFFHaKqjlGcXXHJ:LGkZHsFcukp2QJehSrnFl3GfaOoLCg==
config:
  attestra-auth-email:apiDomain: qa.api.attestrabond.com
  attestra-auth-email:appOrigin: https://qa.attestrabond.com
  attestra-auth-email:captureReservedConcurrency: "5"
  attestra-auth-email:captureWorkerMaxConcurrency: "5"
  attestra-auth-email:senderAddress: verify@qa.info.attestrabond.com
  attestra-auth-email:senderDomain: qa.info.attestrabond.com
  aws:region: us-east-2
  attestra-auth-email:proofKey:
    secure: v1:hI+0ZSoOYWm5usKq:67mGg4+CjpG4ddD3xL4mKwaBSP2xP0AzKR+Ccd3M4JRb5kd44t4g+HkYdsyrCJ1KSPEyhyDZic5FGJfg
