encryptionsalt: v1:SPwlE5x5ETg=:v1:wCZxF6TyEhyKLkUp:5s1PBCz0SVYBVxUcnCKQVh0aTxVDYA==
config:
  aws:region: us-east-2
  attestra-auth-email:appOrigin: https://attestrabond.com
  attestra-auth-email:senderDomain: info.attestrabond.com
  attestra-auth-email:senderAddress: verify@info.attestrabond.com
  attestra-auth-email:proofKey:
    secure: v1:tWDxMngCcgPbuLK6:6HKBar40PMgoDqED55/KrOjEmGg04ckpf+Kk37h2QDYeadTfxT4UdiJNsqS0cPv5UyzfxmvRPclf46jY
