config:
  aws:region: us-east-2
  attestra-auth-email:appOrigin: https://attestrabond.com
  attestra-auth-email:senderDomain: info.attestrabond.com
  attestra-auth-email:senderAddress: verify@info.attestrabond.com
  attestra-auth-email:proofKey:
    secure: v1:yZGfkoLqHQPfnQ1r:002FQOyvGPFnxCfg/BLDHin9AfhIa0u8HkOczVYOUvWjWHdrADK6ocr7M/1JkoYJLT/HOFT87cZFTVbM
encryptionsalt: v1:99BNeZ87EAQ=:v1:/PNM2Jv1AS2+zAE1:8/21IEM5+yRGR/W7UXAD+84GJyXD9w==
